const fs = require('fs');
const https = require('https');
const http = require('http');
const url = require('url');
const nodemailer = require('nodemailer');
require('dotenv').config();

const PORT = 3000;
const API_ENDPOINT = '/extract';

// API keys configuration
const apiKeys = [
  '308ff234ebmsh26b37ab29b3e8abp1c8d0djsne4f46bd4c064',
  'bb9f6eb5c4msh9d3b47786cd371fp13d6e4jsnb9a0c458d1bb',
  '761eba8edcmsheec2c20dc3cffc5p18b22fjsn0254fa46a1fd',
];

const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY; // Replace with your actual DeepSeek API key
const EMAIL_CONFIG = {
  service: 'gmail', // Change if using different provider
  auth: {
    user: process.env.EMAIL_USER, // Replace with your email
    pass: process.env.EMAIL_PASSWORD // Replace with your email password/app-specific password
  }
};

const stateFilePath = './apikey_index.json';

// Load last used API key index
function loadLastUsedIndex() {
  try {
    return JSON.parse(fs.readFileSync(stateFilePath)).lastIndex || 0;
  } catch (err) {
    return 0;
  }
}

// Save current API key index
function saveLastUsedIndex(index) {
  fs.writeFileSync(stateFilePath, JSON.stringify({ lastIndex: index }));
}

// Rotate API keys
function getNextApiKey() {
  const lastIndex = loadLastUsedIndex();
  const nextIndex = (lastIndex + 1) % apiKeys.length;
  saveLastUsedIndex(nextIndex);
  return apiKeys[nextIndex];
}

// Send email with analysis results
async function sendAnalysisEmail(recipientEmail, analysisResult) {
  const transporter = nodemailer.createTransport(EMAIL_CONFIG);
  
  const mailOptions = {
    from: EMAIL_CONFIG.auth.user,
    to: recipientEmail,
    subject: '🏠 Property Investment Analysis Report',
    html: `
      <h1>Property Investment Analysis</h1>
      <div style="background-color:#f0f9ff; padding:20px; border-radius:10px;">
        <pre style="white-space:pre-wrap; font-family:monospace;">${analysisResult}</pre>
      </div>
      <p>This report was generated by our real estate investment analysis system.</p>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`📧 Email sent to: ${recipientEmail}`);
    return info;
  } catch (error) {
    console.error('❌ Email sending failed:', error);
    throw error;
  }
}

// Analyze property data with DeepSeek API
function analyzeWithDeepSeek(propertyData, recipientEmail) {
  const ANALYSIS_PROMPT = `
Eres experto en análisis de rentabilidades financieras para operaciones de activos inmobiliarios. Quiero que en base a la información adjunta aquí y la información que adjunte en formato json:

•⁠  ⁠Ubicación exacta (Calle, numero, código postal, portal, piso, puerta)
•⁠  ⁠Dimensiones (m2)
•⁠  ⁠Distribución de la vivienda actual (si se tiene plano, adjuntar)
•⁠  ⁠Distribución de la vivienda después de la reforma (si se tiene plano, adjuntar)
•⁠  ⁠Condiciones iniciales de compra por parte del propietario
•⁠  ⁠Pago de arras (en %)
•⁠  ⁠Carencia necesaria hasta terminar la reforma (al final de la carencia se pagaría el restante que falta sobre las arras)
•⁠  ⁠Cantidad de equity a aportar en la compra
•⁠  ⁠Cantidad de préstamo y condiciones del préstamo
•⁠  ⁠Estado actual del inmueble (fotos, videos...)
•⁠  ⁠Precio de reforma estimada (si se conoce)
•⁠  ⁠Nota simple actualizada
•⁠  ⁠Etiqueta energética
•⁠  ⁠ITE del edificio
•⁠  ⁠3 últimas actas de juntas


Tienes que ser capaz de analizar, valorar y emitir un informe de rentabilidad de cada operación en la modalidad de Compra-reforma-venta (Contando con 800€-1000€/m2 de reforma estimada) o Compra-Reforma-Cambio de uso a turístico-Alquiler turístico (Analizando el documento de los ADRs adjunto) con el fin de evaluar rápidamente cuál sería el precio de compra ideal analizando el precio medio de venta de la zona a través de idealista.

En la modalidad de Compra-Reforma-Cambio de uso a turístico-Alquiler turístico tienes que ser capaz de analizar cuántas unidades de al menos 35m2 podrían salir y en base a ese número calcular la rentabilidad en base a los ADRs aportados.

Puedes extraer información de idealista para conocer el precio por m2 de compra y alquiler de cada piso propuesto para evaluar su posible rentabilidad.

Para el cálculo de las plusvalías, ten en cuenta este enlace: https://sede.agenciatributaria.gob.es/Sede/ayuda/manuales-videos-folletos/manuales-practicos/manual-tributacion-no-residentes/capitulo-03-tributacion-rentas-comunes-nr/ganancias-patrimoniales/ganancias-patrimoniales-derivadas-venta-inmuebles.html

Este es el mapa de pisos turísticos en Madrid: https://www-2.munimadrid.es/IDEAM_WBGEOPORTAL/visor_ide.iam?ArcGIS=https://sigma.madrid.es/hosted/rest/services/VIVIENDA/VIVIENDAS_TURISTICAS/MapServer

Al finalizar el análisis de rentabilidad quiero que propongas el precio de contraoferta que cumpla con una rentabilidad de al menos un 20% en compra-reforma-venta aportando un resumen como este:

•⁠  ⁠Tipo de operación: CRV
•⁠  ⁠Ubicación: Ciudad, distrito y barrio
•⁠  ⁠Precio de salida: Precio (Precio/m2)
•⁠  ⁠ITP y fiscalidad a pagar:
•⁠  ⁠Honorarios Black Rocket: (Calcúlalos en base al documento "Propuesta Hestia - BR" adjunto)
•⁠  ⁠Coste de reforma + amueblado + imprevistos (800€-1000€/m2 de reforma)
•⁠  ⁠Propuesta de precio de compra (analizando el precio medio del m2 de la zona en esta https://www.idealista.com/sala-de-prensa/informes-precio-vivienda/alquiler/madrid-comunidad/madrid-provincia/madrid/): Precio (Precio/m2)
•⁠  ⁠Ingresos mensuales previstos (si es CRA o R2R)
•⁠  ⁠Rentabilidad neta anual (%)
•⁠  ⁠ROE: (%)
•⁠  ⁠Yield:

Añade al análisis una posible operación de:

•⁠  ⁠Arras del 10-15%
•⁠  ⁠8 meses hasta escrituración
•⁠  ⁠Reforma y reconversión a piso turístico durante el proceso desde el pago de arras hasta la escrituración
•⁠  ⁠Cesión de arras y venta de inmueble con valor añadido.

También quiero que añadas un resumen al final con esta estructura para poder reenviar cada operación a Hestia Viable Capital que nos contrata:

1.⁠ ⁠Tipo de operación: CRV
2.⁠ ⁠Tipo de activo: (Edificio, local o piso)
3.⁠ ⁠Ciudad y distrito o barrio
4.⁠ ⁠Precio de salida
5.⁠ ⁠Arras estimadas
6.⁠ ⁠Inversión total (Arras + reforma y mobiliario + cambio de uso turístico + ITP + Honorarios BR)
5.⁠ ⁠ADR de la zona
6.⁠ ⁠Precio de venta estimado
7.⁠ ⁠ROE


Datos de la propiedad:
${JSON.stringify(propertyData, null, 2)}

Calcula:
- Precio de compra ideal
- Inversión total estimada
- ROI para ambas modalidades
- Recomendación de estrategia
  `;

  const options = {
    hostname: 'api.deepseek.com',
    path: '/v1/chat/completions',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${DEEPSEEK_API_KEY}`
    }
  };

  const req = https.request(options, async (deepseekRes) => {
    console.log("hello world!!")
    console.log('api key deepseek: ', DEEPSEEK_API_KEY);
    let data = '';
    deepseekRes.on('data', (chunk) => data += chunk);
    
    deepseekRes.on('end', () => {
      try {
        const response = JSON.parse(data);
        console.log("deepseek response: ",response);
        
        if (response.choices && response.choices.length > 0) {
          const analysis = response.choices[0].message.content;
          console.log('✅ Received analysis from DeepSeek');
          
          // Send analysis via email
          sendAnalysisEmail(recipientEmail, analysis)
          .then(() => console.log('📩 Analysis report emailed successfully'))
          .catch(err => console.error('❌ Failed to email analysis:', err));
        } else {
          throw new Error('Invalid response from DeepSeek API');
        }
      } catch (err) {
        console.error('❌ DeepSeek response parsing failed on :', err);
      }
    });
  });

  req.on('error', (err) => {
    console.error('❌ DeepSeek API request failed:', err);
  });

  req.write(JSON.stringify({
    model: "deepseek-chat",
    messages: [
      { role: "system", content: "Eres un experto en análisis de inversiones inmobiliarias especializado en reformas y conversión a alojamientos turísticos." },
      { role: "user", content: ANALYSIS_PROMPT }
    ],
    temperature: 0.3,
    max_tokens: 2000
  }));

  req.end();
}

// Fetch property details from Idealista API
function fetchPropertyDetails(propertyId, recipientEmail) {
  const apiKey = getNextApiKey();
  
  const options = {
    method: 'GET',
    hostname: 'idealista7.p.rapidapi.com',
    path: `/propertydetails?propertyId=${propertyId}&location=es&language=en`,
    headers: {
      'x-rapidapi-key': apiKey,
      'x-rapidapi-host': 'idealista7.p.rapidapi.com'
    }
  };

  const req = https.request(options, (apiRes) => {
    let data = '';
    
    apiRes.on('data', (chunk) => data += chunk);
    
    apiRes.on('end', () => {
      console.log(`✅ Used API key: ${apiKey}`);
      
      try {
        const propertyData = JSON.parse(data);
        console.log(`🔍 Fetched property detail (${propertyId})`);
        
        // Send to DeepSeek for analysis
        analyzeWithDeepSeek(propertyData, recipientEmail);
      } catch (err) {
        console.error('❌ JSON parsing failed:', err);
      }
    });
  });

  req.on('error', (err) => {
    console.error(`❌ Idealista API Error with key ${apiKey}:`, err.message);
  });

  req.end();
}

// Create HTTP server
const server = http.createServer((req, res) => {
  const { pathname } = url.parse(req.url, true);
  
  if (req.method === 'POST' && pathname === API_ENDPOINT) {
    let body = '';
    
    req.on('data', chunk => body += chunk);
    
    req.on('end', () => {
      try {
        const payload = JSON.parse(body);
        
        // Validate request format
        if (!payload || typeof payload.emailBody !== 'string' || !payload.recipientEmail) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          return res.end(JSON.stringify({ 
            error: 'Invalid request format',
            message: 'Missing emailBody or recipientEmail'
          }));
        }
        
        // Extract property ID
        const regex = /(?<=https:\/\/www\.idealista\.com\/inmueble\/)\d+/;
        const match = payload.emailBody.match(regex);
        
        if (!match) {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          return res.end(JSON.stringify({ 
            error: 'Property ID not found',
            message: 'No valid Idealista URL found in email body'
          }));
        }
        
        const propertyId = match[0];
        console.log(`🔍 Extracted property ID: ${propertyId}`);
        
        // Start processing and respond immediately
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ 
          status: 'processing',
          message: 'Analysis started. Results will be sent to your email.',
          propertyId
        }));
        
        // Fetch property details and start analysis pipeline
        fetchPropertyDetails(propertyId, payload.recipientEmail);
        
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ 
          error: 'Invalid JSON format',
          message: err.message
        }));
      }
    });
  } else {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ 
      error: 'Not found',
      message: 'Only POST requests to /extract are supported'
    }));
  }
});

// Start the server
server.listen(PORT, () => {
  console.log(`🚀 Server running at http://localhost:${PORT}`);
});